require 'voucherify/version'
require 'voucherify/client'
require 'voucherify/service/async_actions'
require 'voucherify/service/campaigns'
require 'voucherify/service/customers'
require 'voucherify/service/distributions'
require 'voucherify/service/events'
require 'voucherify/service/loyalties'
require 'voucherify/service/orders'
require 'voucherify/service/products'
require 'voucherify/service/redemptions'
require 'voucherify/service/promotions'
require 'voucherify/service/rewards'
require 'voucherify/service/segments'
require 'voucherify/service/segments'
require 'voucherify/service/validation_rules'
require 'voucherify/service/validations'
require 'voucherify/service/vouchers'
require 'voucherify/service/consents'
require 'voucherify/utils'

module Voucherify
end
