=begin
#Voucherify API

#Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

The version of the OpenAPI document: v2018-08-01
Contact: support@voucherify.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module VoucherifySdk
  class ApplicableToEffect
    TO_EVERY = "APPLY_TO_EVERY".freeze
    TO_CHEAPEST = "APPLY_TO_CHEAPEST".freeze
    FROM_CHEAPEST = "APPLY_FROM_CHEAPEST".freeze
    TO_MOST_EXPENSIVE = "APPLY_TO_MOST_EXPENSIVE".freeze
    FROM_MOST_EXPENSIVE = "APPLY_FROM_MOST_EXPENSIVE".freeze

    def self.all_vars
      @all_vars ||= [TO_EVERY, TO_CHEAPEST, FROM_CHEAPEST, TO_MOST_EXPENSIVE, FROM_MOST_EXPENSIVE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ApplicableToEffect.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ApplicableToEffect"
    end
  end
end
