=begin
#Voucherify API

#Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

The version of the OpenAPI document: v2018-08-01
Contact: support@voucherify.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module VoucherifySdk
  class CampaignsSummaryGetResponseBody
    # The type of the object, which is `campaign_summary`.
    attr_accessor :object

    attr_accessor :campaign

    # Total number of redemptions, which includes successful and failed redemptions.
    attr_accessor :redemptions

    # Total number of successful redemptions.
    attr_accessor :redemptions_succeeded

    # Total number of failed redemptions.
    attr_accessor :redemptions_failed

    # Total number of rollbacks, which includes successful and failed rollbacks.
    attr_accessor :rollbacks

    # Total number of successful rollbacks.
    attr_accessor :rollbacks_succeeded

    # Total number of failed rollbacks.
    attr_accessor :rollbacks_failed

    # Total number of validations, which includes successful and failed validations.
    attr_accessor :validations

    # Total number of successful validations.
    attr_accessor :validations_succeeded

    # Total number of failed validations.
    attr_accessor :validations_failed

    # Total amount of orders related to the campaign. This amount is not reduced by `orders_rolledback_amount`. The value is multiplied by `100` to precisely represent 2 decimal places. For example, `$10` is represented as `1000`.
    attr_accessor :orders_amount

    # Total amount of orders that were rolled back and are related to the campaign. The value is multiplied by `100` to precisely represent 2 decimal places. For example, `$10` is represented as `1000`.
    attr_accessor :orders_rolledback_amount

    # Total number of vouchers created within the campaign. Includes vouchers generated when the campaign was created, vouchers added manually, or vouchers generated automatically when a new customer joined the campaign.
    attr_accessor :vouchers_created

    # Total number of vouchers deleted within the campaign. Includes vouchers moved to the bin and vouchers deleted permanently. Vouchers moved to the bin and then deleted permanently are counted once.
    attr_accessor :vouchers_deleted

    # Total number of publications, which includes successful and failed publications.
    attr_accessor :publications

    # Total number of successful publications.
    attr_accessor :publications_succeeded

    # Total number of failed publications.
    attr_accessor :publications_failed

    # Total amount of discounts related to the campaign. This amount is not reduced by the `rolledback_discounted_amount`. The value is multiplied by `100` to precisely represent 2 decimal places. For example, `$10` is represented as `1000`.
    attr_accessor :discounted_amount

    # Total amount of discounts orders that were rolled back and are related to the campaign. The value is multiplied by `100` to precisely represent 2 decimal places. For example, `$10` is represented as `1000`.
    attr_accessor :rolledback_discounted_amount

    # The total credit amount for all created gift cards. The value is multiplied by `100` to precisely represent 2 decimal places. For example, `$10` is represented as `1000`.
    attr_accessor :created_vouchers_amount

    # The total credit amount that was added. The value is multiplied by `100` to precisely represent 2 decimal places. For example, `$10` is represented as `1000`.
    attr_accessor :amount_added

    # The total credit amount that was deleted by deleting gift cards. The value is multiplied by `100` to precisely represent 2 decimal places. For example, `$10` is represented as `1000`.
    attr_accessor :amount_deleted

    # The total credit amount that was redeemed. This amount is not reduced by the `amount_rolledback`. The value is multiplied by `100` to precisely represent 2 decimal places. For example, `$10` is represented as `1000`.
    attr_accessor :amount_redeemed

    # The total credit amount that was rolled back. The value is multiplied by `100` to precisely represent 2 decimal places. For example, `$10` is represented as `1000`.
    attr_accessor :amount_rolledback

    # The total credit amount that was subtracted. The value is multiplied by `100` to precisely represent 2 decimal places. For example, `$10` is represented as `1000`.
    attr_accessor :amount_subtracted

    # Total number of points added to newly created loyalty cards. This also counts points added for the loyalty cards which are created by importing a CSV file to a campaign.
    attr_accessor :created_vouchers_points

    # Total number of points that were deleted.
    attr_accessor :points_deleted

    # Total number of points that were subtracted.
    attr_accessor :points_subtracted

    # Total number of points that were added. This includes points added manually or automatically by redeeming a reward that adds loyalty points to cards in this campaign.
    attr_accessor :points_added

    # Total number of points that were rewarded to loyalty cards through earning rules. This includes pending points that were activated.
    attr_accessor :points_rewarded

    # Total number of points that were redeemed for rewards.
    attr_accessor :points_redeemed

    # Total number of points that were rolled back for reward redemptions.
    attr_accessor :points_rolledback

    # Total number of points that have expired.
    attr_accessor :points_expired

    # Total number of points transferred out of loyalty cards covered by the campaign.
    attr_accessor :points_transferred_out

    # Total number of points transferred into loyalty cards covered by the campaign.
    attr_accessor :points_transferred_in

    # Total number of pending points that were added either as part of earning rules or added manually to an existing pending point bucket. Pending points that were activated manually or automatically or that were canceled do not affect this number.
    attr_accessor :pending_points_added

    # Total number of pending points that were subtracted from existing pending point buckets.
    attr_accessor :pending_points_subtracted

    # Total number of pending points that were activated manually or automatically.
    attr_accessor :pending_points_activated

    # Total number of pending points that were canceled.
    attr_accessor :pending_points_canceled

    # Total number of all referred customers.
    attr_accessor :referred_customers

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'object' => :'object',
        :'campaign' => :'campaign',
        :'redemptions' => :'redemptions',
        :'redemptions_succeeded' => :'redemptions_succeeded',
        :'redemptions_failed' => :'redemptions_failed',
        :'rollbacks' => :'rollbacks',
        :'rollbacks_succeeded' => :'rollbacks_succeeded',
        :'rollbacks_failed' => :'rollbacks_failed',
        :'validations' => :'validations',
        :'validations_succeeded' => :'validations_succeeded',
        :'validations_failed' => :'validations_failed',
        :'orders_amount' => :'orders_amount',
        :'orders_rolledback_amount' => :'orders_rolledback_amount',
        :'vouchers_created' => :'vouchers_created',
        :'vouchers_deleted' => :'vouchers_deleted',
        :'publications' => :'publications',
        :'publications_succeeded' => :'publications_succeeded',
        :'publications_failed' => :'publications_failed',
        :'discounted_amount' => :'discounted_amount',
        :'rolledback_discounted_amount' => :'rolledback_discounted_amount',
        :'created_vouchers_amount' => :'created_vouchers_amount',
        :'amount_added' => :'amount_added',
        :'amount_deleted' => :'amount_deleted',
        :'amount_redeemed' => :'amount_redeemed',
        :'amount_rolledback' => :'amount_rolledback',
        :'amount_subtracted' => :'amount_subtracted',
        :'created_vouchers_points' => :'created_vouchers_points',
        :'points_deleted' => :'points_deleted',
        :'points_subtracted' => :'points_subtracted',
        :'points_added' => :'points_added',
        :'points_rewarded' => :'points_rewarded',
        :'points_redeemed' => :'points_redeemed',
        :'points_rolledback' => :'points_rolledback',
        :'points_expired' => :'points_expired',
        :'points_transferred_out' => :'points_transferred_out',
        :'points_transferred_in' => :'points_transferred_in',
        :'pending_points_added' => :'pending_points_added',
        :'pending_points_subtracted' => :'pending_points_subtracted',
        :'pending_points_activated' => :'pending_points_activated',
        :'pending_points_canceled' => :'pending_points_canceled',
        :'referred_customers' => :'referred_customers'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'object' => :'String',
        :'campaign' => :'CampaignBase',
        :'redemptions' => :'Integer',
        :'redemptions_succeeded' => :'Integer',
        :'redemptions_failed' => :'Integer',
        :'rollbacks' => :'Integer',
        :'rollbacks_succeeded' => :'Integer',
        :'rollbacks_failed' => :'Integer',
        :'validations' => :'Integer',
        :'validations_succeeded' => :'Integer',
        :'validations_failed' => :'Integer',
        :'orders_amount' => :'Integer',
        :'orders_rolledback_amount' => :'Integer',
        :'vouchers_created' => :'Integer',
        :'vouchers_deleted' => :'Integer',
        :'publications' => :'Integer',
        :'publications_succeeded' => :'Integer',
        :'publications_failed' => :'Integer',
        :'discounted_amount' => :'Integer',
        :'rolledback_discounted_amount' => :'Integer',
        :'created_vouchers_amount' => :'Integer',
        :'amount_added' => :'Integer',
        :'amount_deleted' => :'Integer',
        :'amount_redeemed' => :'Integer',
        :'amount_rolledback' => :'Integer',
        :'amount_subtracted' => :'Integer',
        :'created_vouchers_points' => :'Integer',
        :'points_deleted' => :'Integer',
        :'points_subtracted' => :'Integer',
        :'points_added' => :'Integer',
        :'points_rewarded' => :'Integer',
        :'points_redeemed' => :'Integer',
        :'points_rolledback' => :'Integer',
        :'points_expired' => :'Integer',
        :'points_transferred_out' => :'Integer',
        :'points_transferred_in' => :'Integer',
        :'pending_points_added' => :'Integer',
        :'pending_points_subtracted' => :'Integer',
        :'pending_points_activated' => :'Integer',
        :'pending_points_canceled' => :'Integer',
        :'referred_customers' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'object',
        :'redemptions',
        :'redemptions_succeeded',
        :'redemptions_failed',
        :'rollbacks',
        :'rollbacks_succeeded',
        :'rollbacks_failed',
        :'validations',
        :'validations_succeeded',
        :'validations_failed',
        :'orders_amount',
        :'orders_rolledback_amount',
        :'vouchers_created',
        :'vouchers_deleted',
        :'publications',
        :'publications_succeeded',
        :'publications_failed',
        :'discounted_amount',
        :'rolledback_discounted_amount',
        :'created_vouchers_amount',
        :'amount_added',
        :'amount_deleted',
        :'amount_redeemed',
        :'amount_rolledback',
        :'amount_subtracted',
        :'created_vouchers_points',
        :'points_deleted',
        :'points_subtracted',
        :'points_added',
        :'points_rewarded',
        :'points_redeemed',
        :'points_rolledback',
        :'points_expired',
        :'points_transferred_out',
        :'points_transferred_in',
        :'pending_points_added',
        :'pending_points_subtracted',
        :'pending_points_activated',
        :'pending_points_canceled',
        :'referred_customers'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        h[k.to_sym] = v
      }

      if attributes.key?(:'object')
        self.object = attributes[:'object']
      else
        self.object = 'campaign_summary'
      end

      if attributes.key?(:'campaign')
        self.campaign = attributes[:'campaign']
      end

      if attributes.key?(:'redemptions')
        self.redemptions = attributes[:'redemptions']
      end

      if attributes.key?(:'redemptions_succeeded')
        self.redemptions_succeeded = attributes[:'redemptions_succeeded']
      end

      if attributes.key?(:'redemptions_failed')
        self.redemptions_failed = attributes[:'redemptions_failed']
      end

      if attributes.key?(:'rollbacks')
        self.rollbacks = attributes[:'rollbacks']
      end

      if attributes.key?(:'rollbacks_succeeded')
        self.rollbacks_succeeded = attributes[:'rollbacks_succeeded']
      end

      if attributes.key?(:'rollbacks_failed')
        self.rollbacks_failed = attributes[:'rollbacks_failed']
      end

      if attributes.key?(:'validations')
        self.validations = attributes[:'validations']
      end

      if attributes.key?(:'validations_succeeded')
        self.validations_succeeded = attributes[:'validations_succeeded']
      end

      if attributes.key?(:'validations_failed')
        self.validations_failed = attributes[:'validations_failed']
      end

      if attributes.key?(:'orders_amount')
        self.orders_amount = attributes[:'orders_amount']
      end

      if attributes.key?(:'orders_rolledback_amount')
        self.orders_rolledback_amount = attributes[:'orders_rolledback_amount']
      end

      if attributes.key?(:'vouchers_created')
        self.vouchers_created = attributes[:'vouchers_created']
      end

      if attributes.key?(:'vouchers_deleted')
        self.vouchers_deleted = attributes[:'vouchers_deleted']
      end

      if attributes.key?(:'publications')
        self.publications = attributes[:'publications']
      end

      if attributes.key?(:'publications_succeeded')
        self.publications_succeeded = attributes[:'publications_succeeded']
      end

      if attributes.key?(:'publications_failed')
        self.publications_failed = attributes[:'publications_failed']
      end

      if attributes.key?(:'discounted_amount')
        self.discounted_amount = attributes[:'discounted_amount']
      end

      if attributes.key?(:'rolledback_discounted_amount')
        self.rolledback_discounted_amount = attributes[:'rolledback_discounted_amount']
      end

      if attributes.key?(:'created_vouchers_amount')
        self.created_vouchers_amount = attributes[:'created_vouchers_amount']
      end

      if attributes.key?(:'amount_added')
        self.amount_added = attributes[:'amount_added']
      end

      if attributes.key?(:'amount_deleted')
        self.amount_deleted = attributes[:'amount_deleted']
      end

      if attributes.key?(:'amount_redeemed')
        self.amount_redeemed = attributes[:'amount_redeemed']
      end

      if attributes.key?(:'amount_rolledback')
        self.amount_rolledback = attributes[:'amount_rolledback']
      end

      if attributes.key?(:'amount_subtracted')
        self.amount_subtracted = attributes[:'amount_subtracted']
      end

      if attributes.key?(:'created_vouchers_points')
        self.created_vouchers_points = attributes[:'created_vouchers_points']
      end

      if attributes.key?(:'points_deleted')
        self.points_deleted = attributes[:'points_deleted']
      end

      if attributes.key?(:'points_subtracted')
        self.points_subtracted = attributes[:'points_subtracted']
      end

      if attributes.key?(:'points_added')
        self.points_added = attributes[:'points_added']
      end

      if attributes.key?(:'points_rewarded')
        self.points_rewarded = attributes[:'points_rewarded']
      end

      if attributes.key?(:'points_redeemed')
        self.points_redeemed = attributes[:'points_redeemed']
      end

      if attributes.key?(:'points_rolledback')
        self.points_rolledback = attributes[:'points_rolledback']
      end

      if attributes.key?(:'points_expired')
        self.points_expired = attributes[:'points_expired']
      end

      if attributes.key?(:'points_transferred_out')
        self.points_transferred_out = attributes[:'points_transferred_out']
      end

      if attributes.key?(:'points_transferred_in')
        self.points_transferred_in = attributes[:'points_transferred_in']
      end

      if attributes.key?(:'pending_points_added')
        self.pending_points_added = attributes[:'pending_points_added']
      end

      if attributes.key?(:'pending_points_subtracted')
        self.pending_points_subtracted = attributes[:'pending_points_subtracted']
      end

      if attributes.key?(:'pending_points_activated')
        self.pending_points_activated = attributes[:'pending_points_activated']
      end

      if attributes.key?(:'pending_points_canceled')
        self.pending_points_canceled = attributes[:'pending_points_canceled']
      end

      if attributes.key?(:'referred_customers')
        self.referred_customers = attributes[:'referred_customers']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      object_validator = EnumAttributeValidator.new('String', ["campaign_summary"])
      return false unless object_validator.valid?(@object)
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          object == o.object &&
          campaign == o.campaign &&
          redemptions == o.redemptions &&
          redemptions_succeeded == o.redemptions_succeeded &&
          redemptions_failed == o.redemptions_failed &&
          rollbacks == o.rollbacks &&
          rollbacks_succeeded == o.rollbacks_succeeded &&
          rollbacks_failed == o.rollbacks_failed &&
          validations == o.validations &&
          validations_succeeded == o.validations_succeeded &&
          validations_failed == o.validations_failed &&
          orders_amount == o.orders_amount &&
          orders_rolledback_amount == o.orders_rolledback_amount &&
          vouchers_created == o.vouchers_created &&
          vouchers_deleted == o.vouchers_deleted &&
          publications == o.publications &&
          publications_succeeded == o.publications_succeeded &&
          publications_failed == o.publications_failed &&
          discounted_amount == o.discounted_amount &&
          rolledback_discounted_amount == o.rolledback_discounted_amount &&
          created_vouchers_amount == o.created_vouchers_amount &&
          amount_added == o.amount_added &&
          amount_deleted == o.amount_deleted &&
          amount_redeemed == o.amount_redeemed &&
          amount_rolledback == o.amount_rolledback &&
          amount_subtracted == o.amount_subtracted &&
          created_vouchers_points == o.created_vouchers_points &&
          points_deleted == o.points_deleted &&
          points_subtracted == o.points_subtracted &&
          points_added == o.points_added &&
          points_rewarded == o.points_rewarded &&
          points_redeemed == o.points_redeemed &&
          points_rolledback == o.points_rolledback &&
          points_expired == o.points_expired &&
          points_transferred_out == o.points_transferred_out &&
          points_transferred_in == o.points_transferred_in &&
          pending_points_added == o.pending_points_added &&
          pending_points_subtracted == o.pending_points_subtracted &&
          pending_points_activated == o.pending_points_activated &&
          pending_points_canceled == o.pending_points_canceled &&
          referred_customers == o.referred_customers
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [object, campaign, redemptions, redemptions_succeeded, redemptions_failed, rollbacks, rollbacks_succeeded, rollbacks_failed, validations, validations_succeeded, validations_failed, orders_amount, orders_rolledback_amount, vouchers_created, vouchers_deleted, publications, publications_succeeded, publications_failed, discounted_amount, rolledback_discounted_amount, created_vouchers_amount, amount_added, amount_deleted, amount_redeemed, amount_rolledback, amount_subtracted, created_vouchers_points, points_deleted, points_subtracted, points_added, points_rewarded, points_redeemed, points_rolledback, points_expired, points_transferred_out, points_transferred_in, pending_points_added, pending_points_subtracted, pending_points_activated, pending_points_canceled, referred_customers].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = VoucherifySdk.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
