=begin
#Voucherify API

#Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

The version of the OpenAPI document: v2018-08-01
Contact: support@voucherify.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module VoucherifySdk
  class DiscountAmountVouchersEffectTypes
    ORDER = "APPLY_TO_ORDER".freeze
    ITEMS = "APPLY_TO_ITEMS".freeze
    ITEMS_PROPORTIONALLY = "APPLY_TO_ITEMS_PROPORTIONALLY".freeze
    ITEMS_PROPORTIONALLY_BY_QUANTITY = "APPLY_TO_ITEMS_PROPORTIONALLY_BY_QUANTITY".freeze
    ITEMS_BY_QUANTITY = "APPLY_TO_ITEMS_BY_QUANTITY".freeze

    def self.all_vars
      @all_vars ||= [ORDER, ITEMS, ITEMS_PROPORTIONALLY, ITEMS_PROPORTIONALLY_BY_QUANTITY, ITEMS_BY_QUANTITY].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DiscountAmountVouchersEffectTypes.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DiscountAmountVouchersEffectTypes"
    end
  end
end
