name: Publish SDK

on:
  push:
    tags:
      - v*

jobs:
  publish:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Ruby
        uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: bundle install

      - name: Build GEM
        run: gem build *.gemspec
        
      - name: Push GEM
        run: gem push *.gem --debug
        env:
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
