name: Publish SDK

on:
  push:
    tags:
      - v*

jobs:
  publish:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5

      - name: Set up Ruby
        uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: bundle install

      - name: Build GEM
        run: gem build *.gemspec
        
      - name: Push GEM
        run: gem push *.gem --debug
        env:
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
